//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMTool.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int Id { get; set; }
        public int FK_Task { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> ProjectOwner { get; set; }
        public Nullable<decimal> ActualCost { get; set; }
        public Nullable<int> FK_Project { get; set; }
        public Nullable<int> FK_Milestone { get; set; }
        public Nullable<int> FK_MilestoneOwner { get; set; }
        public Nullable<int> CompletedBy { get; set; }
        public Nullable<System.DateTime> CompletedOn { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<int> FK_ProjectOwner { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
